# Streamlit app config

[theme]
primaryColor = "#0ea5e9"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f6f7fb"
textColor = "#111827"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[client]
toolbarMode = "viewer"

[logger]
level = "info"
